CREATE TABLE SacramentExport_NonMem(
        NonMemberID TEXT,
        Description TEXT,
        LastName TEXT,
        FirstName TEXT,
        MiddleName TEXT,
        Suffix TEXT,
        MaidenName TEXT,
        DOB TEXT,
        Gender TEXT,
        Father TEXT,
        Mother TEXT,
        BirthPlace TEXT,
        ChristianWitness TEXT,
        BaptismName TEXT,
        ConfirmationName TEXT,
        MarriageSpouseName TEXT,
        SacDate TEXT,
        DeceasedDate TEXT,
        ProfOfFaith TEXT,
        Status TEXT,
        PerformedBy TEXT,
        PlaceID TEXT,
        Place TEXT,
        Address1 TEXT,
        CityState TEXT,
        City TEXT,
        State TEXT,
        Zip TEXT,
        Country TEXT,
        DeathCityState TEXT,
        DeceasedPlaceofBurial TEXT,
        BurialCity TEXT,
        BurialState TEXT,
        BurialCountry TEXT,
        GenNotes TEXT,
        Volume TEXT,
        Page TEXT,
        Entry TEXT,
        Sponsor1 TEXT,
        Sponsor2 TEXT,
        Proxy1 TEXT,
        Proxy2 TEXT,

-- Add a composite UNIQUE constraint
UNIQUE(Description, LastName, FirstName, DOB) );

CREATE TABLE [SacramentBooks_NonMem](
        [NonMemberID] TEXT,
        [Sacrament] TEXT,
        [Date] TEXT,
        [Volume] TEXT,
        [Page] TEXT,
        [Entry] TEXT
    );

CREATE TABLE [Sacraments_NonMem](
        [NonMemberID] TEXT,
        [BirthPlace] TEXT,
        [FathersName] TEXT,
        [MothersName] TEXT,
        [MothersMaidenName] TEXT,
        [BaptismName] TEXT,
        [BaptismDate] TEXT,
        [BaptismStatus] TEXT,
        [BaptismPlace] TEXT,
        [BaptismStreetAddress] TEXT,
        [BaptismCity] TEXT,
        [BaptismState] TEXT,
        [BaptismZip] TEXT,
        [BaptismCountry] TEXT,
        [BaptismCelebrant] TEXT,
        [BaptismNotes] TEXT,
        [ReconciliationDate] TEXT,
        [FirstCommunionDate] TEXT,
        [FirstCommunionStatus] TEXT,
        [FirstCommunionPlace] TEXT,
        [FirstCommunionStreetAddress] TEXT,
        [FirstCommunionCity] TEXT,
        [FirstCommunionState] TEXT,
        [FirstCommunionZip] TEXT,
        [FirstCommunionCountry] TEXT,
        [FirstCommunionCelebrant] TEXT,
        [FirstCommunionNotes] TEXT,
        [ConfirmationName] TEXT,
        [ConfirmationDate] TEXT,
        [ConfirmationStatus] TEXT,
        [ConfirmationPlace] TEXT,
        [ConfirmationStreetAddress] TEXT,
        [ConfirmationCity] TEXT,
        [ConfirmationState] TEXT,
        [ConfirmationZip] TEXT,
        [ConfirmationCountry] TEXT,
        [ConfirmationCelebrant] TEXT,
        [ConfirmationNotes] TEXT,
        [RCIADate] TEXT,
        [RCIAStatus] TEXT,
        [RCIAPlace] TEXT,
        [RCIAStreetAddress] TEXT,
        [RCIACity] TEXT,
        [RCIAState] TEXT,
        [RCIAZip] TEXT,
        [RCIACountry] TEXT,
        [RCIACelebrant] TEXT,
        [RCIANotes] TEXT,
        [MarriageSpouseName] TEXT,
        [MarriageDate] TEXT,
        [MarriageStatus] TEXT,
        [MarriagePlace] TEXT,
        [MarriageStreetAddress] TEXT,
        [MarriageCity] TEXT,
        [MarriageState] TEXT,
        [MarriageZip] TEXT,
        [MarriageCountry] TEXT,
        [MarriageCelebrant] TEXT,
        [MarriageNotes] TEXT,
        [DeceasedDate] TEXT,
        [DeceasedStatus] TEXT,
        [DeceasedPlace] TEXT,
        [DeceasedStreetAddress] TEXT,
        [DeceasedCity] TEXT,
        [DeceasedState] TEXT,
        [DeceasedZip] TEXT,
        [DeceasedCountry] TEXT,
        [DeceasedCelebrant] TEXT,
        [DeceasedNotes] TEXT,
        [DeceasedPlaceofBurial] TEXT,
        [DeathCityState] TEXT
    );

CREATE TABLE [SacramentSponsors_NonMem](
        [NonMemberID] TEXT,
        [Sacrament] TEXT,
        [SponsorName] TEXT,
        [SponsorType] TEXT,
        [Proxy] TEXT
    );

CREATE TABLE [NonMembers]
    (
        [NonMemberID] TEXT,
        [FirstName] TEXT,
        [LastName] TEXT,
        [MiddleName] TEXT,
        [Suffix] Text,
        [Title] Text,
        MaidenName Text,
        Gender TEXT,
        DOB text,
        DateDeceased TEXT,
        Deceased TEXT
    );